---
substitutions:
  name: esp32-s3-box-3
  friendly_name: ESP32 S3 Box 3
  loading_illustration_file: https://github.com/esphome/wake-word-voice-assistants/raw/main/casita/loading_320_240.png
  idle_illustration_file: https://github.com/esphome/wake-word-voice-assistants/raw/main/casita/idle_320_240.png
  listening_illustration_file: https://github.com/esphome/wake-word-voice-assistants/raw/main/casita/listening_320_240.png
  thinking_illustration_file: https://github.com/esphome/wake-word-voice-assistants/raw/main/casita/thinking_320_240.png
  replying_illustration_file: https://github.com/esphome/wake-word-voice-assistants/raw/main/casita/replying_320_240.png
  error_illustration_file: https://github.com/esphome/wake-word-voice-assistants/raw/main/casita/error_320_240.png
  timer_finished_illustration_file: https://github.com/esphome/wake-word-voice-assistants/raw/main/casita/timer_finished_320_240.png
  font_family: Roboto
  font_glyphsets: GF_Latin_Core
  # These unique characters have been extracted from every test file of every language of the firmware.
  # This is used to make sure the font supports all characters that can be displayed.
  # If you add new text to the display, you may need to add characters here.
  # DO NOT remove characters from this list.
  font_glyphs: ' !"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~°'
  volume_unit: gal
  # Display colors
  loading_color_hex: "FFFFFF"
  idle_color_hex: "FFFFFF"
  listening_color_hex: "FFFFFF"
  thinking_color_hex: "FFFFFF"
  replying_color_hex: "FFFFFF"
  error_color_hex: "000000"
  # Voice assistant phases
  voice_assist_idle_phase_id: "1"
  voice_assist_listening_phase_id: "2"
  voice_assist_thinking_phase_id: "3"
  voice_assist_replying_phase_id: "4"
  voice_assist_not_ready_phase_id: "10"
  voice_assist_error_phase_id: "11"
  voice_assist_muted_phase_id: "12"
  voice_assist_timer_finished_phase_id: "20"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.12.0

esp32:
  board: esp32-s3-box-3
  framework:
    type: esp-idf

ota:
  - platform: esphome
    id: ota_esphome

logger:
  hardware_uart: USB_SERIAL_JTAG

time:
  - platform: homeassistant
    id: ha_time

wifi:
  ap:
  on_connect:
    - script.execute: draw_display
  on_disconnect:
    - script.execute: draw_display

api:
  on_client_connected:
    - script.execute: draw_display
  on_client_disconnected:
    - script.execute: draw_display

captive_portal:

button:
  - platform: factory_reset
    id: factory_reset_btn
    internal: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    id: left_top_button
    internal: true
    on_multi_click:
      - timing:
          - ON for at least 50ms
          - OFF for at least 50ms
        then:
          - switch.turn_off: timer_ringing
      - timing:
          - ON for at least 10s
        then:
          - button.press: factory_reset_btn

switch:
  - platform: gpio
    name: Speaker Enable
    pin: GPIO46
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    disabled_by_default: true

  - platform: template
    name: Mute
    id: mute
    icon: mdi:microphone-off
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "Mute ON"
      - voice_assistant.stop
      - micro_wake_word.stop
      - script.execute: draw_display
    on_turn_off:
      - logger.log: "Mute OFF"
      - script.execute: start_wake_word
      - script.execute: draw_display

output:
  - platform: ledc
    pin: GPIO47
    id: backlight_output

light:
  - platform: monochromatic
    id: led
    name: Screen
    output: backlight_output
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    default_transition_length: 0s

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO45
    i2s_bclk_pin: GPIO17
    i2s_mclk_pin: GPIO2

audio_adc:
  - platform: es7210
    id: es7210_adc
    bits_per_sample: 16bit
    sample_rate: 16000

audio_dac:
  - platform: es8311
    id: es8311_dac
    bits_per_sample: 16bit
    sample_rate: 48000

microphone:
  - platform: i2s_audio
    id: box_mic
    sample_rate: 16000
    i2s_din_pin: GPIO16
    bits_per_sample: 16bit
    adc_type: external

speaker:
  - platform: i2s_audio
    id: box_speaker
    i2s_audio_id: i2s_audio_bus
    i2s_dout_pin: GPIO15
    bits_per_sample: 16bit
    dac_type: external
    channel: mono
    sample_rate: 48000

media_player:
  - platform: speaker
    name: Speaker
    id: box_media_player
    speaker: box_speaker
    announcement_pipeline:
      speaker: box_speaker
    on_state:
      then:
        - script.execute: draw_display

voice_assistant:
  id: va
  microphone: box_mic
  media_player: box_media_player
  use_wake_word: false
  on_client_connected:
    then:
      - script.execute: draw_display
      - script.execute: start_wake_word
  on_client_disconnected:
    then:
      - script.execute: draw_display
      - micro_wake_word.stop
  on_listening:
    then:
      - script.execute: draw_display
  on_thinking:
    then:
      - script.execute: draw_display
  on_tts_start:
    then:
      - script.execute: draw_display
  on_tts_end:
    then:
      - script.execute: draw_display
  on_error:
    then:
      - script.execute: draw_display
  on_timer_started:
    then:
      - script.execute: draw_display
  on_timer_updated:
    then:
      - script.execute: draw_display
  on_timer_finished:
    then:
      - switch.turn_on: timer_ringing
      - script.execute: draw_display

micro_wake_word:
  id: mww
  models:
    - model: https://github.com/esphome/micro-wake-word-models/raw/main/models/hey_jarvis.json
  on_wake_word_detected:
    then:
      - if:
          condition:
            switch.is_off: mute
          then:
            - voice_assistant.start
            - script.execute: draw_display

select:
  - platform: template
    entity_category: config
    name: Wake word engine location
    id: wake_word_engine_location
    icon: mdi:account-voice
    optimistic: true
    restore_value: true
    options:
      - In Home Assistant
      - On device
    initial_option: On device
    on_value:
      - lambda: |-
          auto x = id(wake_word_engine_location).state;
          if (x == "In Home Assistant") {
            id(va).set_use_wake_word(true);
          } else {
            id(va).set_use_wake_word(false);
          }
      - if:
          condition:
            lambda: return id(wake_word_engine_location).state == "In Home Assistant";
          then:
            - micro_wake_word.stop
            - delay: 500ms
            - if:
                condition:
                  switch.is_off: mute
                then:
                  - lambda: id(va).set_use_wake_word(true);
                  - voice_assistant.start_continuous:
          else:
            - lambda: id(va).set_use_wake_word(false);
            - script.execute: start_wake_word

globals:
  - id: init_in_progress
    type: bool
    restore_value: false
    initial_value: "true"
  - id: voice_assistant_phase
    type: int
    restore_value: false
    initial_value: ${voice_assist_not_ready_phase_id}
  - id: global_first_active_timer
    type: voice_assistant::Timer
    restore_value: false
  - id: global_is_timer_active
    type: bool
    restore_value: false
  - id: global_first_timer
    type: voice_assistant::Timer
    restore_value: false
  - id: global_is_timer
    type: bool
    restore_value: false

script:
  - id: start_wake_word
    mode: restart
    then:
      - if:
          condition:
            lambda: return id(wake_word_engine_location).state == "On device";
          then:
            - micro_wake_word.start

  - id: draw_display
    mode: restart
    then:
      - component.update: s3_box_lcd

text_sensor:
  - id: text_request
    platform: template
    on_value:
      lambda: |-
        if(id(text_request).state.length()>32) {
          std::string name = id(text_request).state.c_str();
          std::string truncated = esphome::str_truncate(name.c_str(),31);
          id(text_request).state = (truncated+"...").c_str();
        }

  - id: text_response
    platform: template
    on_value:
      lambda: |-
        if(id(text_response).state.length()>32) {
          std::string name = id(text_response).state.c_str();
          std::string truncated = esphome::str_truncate(name.c_str(),31);
          id(text_response).state = (truncated+"...").c_str();
        }

color:
  - id: idle_color
    hex: ${idle_color_hex}
  - id: listening_color
    hex: ${listening_color_hex}
  - id: thinking_color
    hex: ${thinking_color_hex}
  - id: replying_color
    hex: ${replying_color_hex}
  - id: idle_text_color
    hex: "000000"
  - id: loading_color
    hex: ${loading_color_hex}
  - id: error_color
    hex: ${error_color_hex}
  - id: active_timer_color
    hex: "26ed3a"
  - id: paused_timer_color
    hex: "3b89e3"

image:
  - file: ${error_illustration_file}
    id: casita_error
    resize: 320x240
    type: RGB
    transparency: alpha_channel

  - file: ${idle_illustration_file}
    id: casita_idle
    resize: 320x240
    type: RGB
    transparency: alpha_channel

  - file: ${listening_illustration_file}
    id: casita_listening
    resize: 320x240
    type: RGB
    transparency: alpha_channel

  - file: ${thinking_illustration_file}
    id: casita_thinking
    resize: 320x240
    type: RGB
    transparency: alpha_channel

  - file: ${replying_illustration_file}
    id: casita_replying
    resize: 320x240
    type: RGB
    transparency: alpha_channel

  - file: ${loading_illustration_file}
    id: casita_initializing
    resize: 320x240
    type: RGB
    transparency: alpha_channel

  - file: ${timer_finished_illustration_file}
    id: casita_timer_finished
    resize: 320x240
    type: RGB
    transparency: alpha_channel

font:
  - file:
      type: gfonts
      family: ${font_family}
      weight: 300
      italic: true
    id: font_request
    size: 15
    glyphsets:
      - ${font_glyphsets}

  - file:
      type: gfonts
      family: ${font_family}
      weight: 300
    id: font_response
    size: 15
    glyphsets:
      - ${font_glyphsets}

  - file:
      type: gfonts
      family: ${font_family}
      weight: 300
    id: font_timer
    size: 30
    glyphsets:
      - ${font_glyphsets}

text:
  - platform: template
    id: text_response_line_1
  - platform: template
    id: text_response_line_2
  - platform: template
    id: text_response_line_3

switch:
  - platform: template
    id: timer_ringing
    name: Timer Ringing
    internal: true
    optimistic: true
    restore_mode: ALWAYS_OFF

display:
  - platform: ili9xxx
    id: s3_box_lcd
    model: S3BOX
    invert_colors: false
    data_rate: 40MHz
    cs_pin: 5
    dc_pin: 4
    reset_pin:
      number: 48
      inverted: true
    update_interval: 1s
    pages:
      - id: idle_page
        lambda: |-
          it.fill(id(idle_color));
          it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_idle), ImageAlign::CENTER);
          auto now = id(ha_time).now();
          if (now.is_valid()) {
            const bool blink = (now.second % 2) == 0;
            char buf[6];
            now.strftime(buf, sizeof(buf), blink ? "%I:%M" : "%I %M");
            if (buf[0] == '0') memmove(buf, buf + 1, strlen(buf));
            it.print(160, 28, id(font_timer), id(idle_text_color), TextAlign::TOP_CENTER, buf);
          }
          id(draw_timer_timeline).execute();
          id(draw_active_timer_widget).execute();

      - id: listening_page
        lambda: |-
          it.fill(id(listening_color));
          it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_listening), ImageAlign::CENTER);
          id(draw_timer_timeline).execute();

      - id: thinking_page
        lambda: |-
          it.fill(id(thinking_color));
          it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_thinking), ImageAlign::CENTER);
          id(draw_timer_timeline).execute();

      - id: replying_page
        lambda: |-
          it.fill(id(replying_color));
          it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_replying), ImageAlign::CENTER);
          id(draw_timer_timeline).execute();

      - id: timer_finished_page
        lambda: |-
          it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_timer_finished), ImageAlign::CENTER);

      - id: error_page
        lambda: |-
          it.fill(id(error_color));
          it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_error), ImageAlign::CENTER);

      - id: no_ha_page
        lambda: |-
          it.image((it.get_width() / 2), (it.get_height() / 2), id(error_no_ha), ImageAlign::CENTER);

      - id: no_wifi_page
        lambda: |-
          it.image((it.get_width() / 2), (it.get_height() / 2), id(error_no_wifi), ImageAlign::CENTER);

      - id: initializing_page
        lambda: |-
          it.fill(id(loading_color));
          it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_initializing), ImageAlign::CENTER);

      - id: muted_page
        lambda: |-
          it.fill(Color::BLACK);
          id(draw_timer_timeline).execute();
          id(draw_active_timer_widget).execute();
